apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mp-web-client.fullname" . }}
  labels:
    {{ include "mp-web-client.labels" . | nindent 4 }}
data:
  REACT_APP_IOT_DATA_MARKETPLACE_CONTRACT_ADDRESS: {{ required "A valid .Values.reactAppIoTDataMarketplaceContractAddress entry required!" .Values.reactAppIoTDataMarketplaceContractAddress }}
