# Default values for mp-web-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 543164192837.dkr.ecr.eu-central-1.amazonaws.com/mp-web-client
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

recreationFlag: 1

global:
  recreationFlag: 1

graphQlEndpoint: ""

service:
  portName: http-8040
  nodePort: 30445
  type: NodePort
  port: 8040
  targetPort: 8040

reactAppIoTDataMarketplaceContractAddress: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
